# Generated by Django 3.2.10 on 2022-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwtapp", "0004_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("f", "Feature"),
                            ("i", "Infographic"),
                            ("g", "Gallery"),
                        ],
                        max_length=1,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True, null=True)),
                ("infographic", models.ImageField(blank=True, null=True, upload_to="")),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureStory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jwtapp.story",),
        ),
        migrations.CreateModel(
            name="GalleryStory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jwtapp.story",),
        ),
        migrations.CreateModel(
            name="InfographicStory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jwtapp.story",),
        ),
    ]
