# Generated by Django 3.2.10 on 2022-01-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwtapp", "0005_featurestory_gallerystory_infographicstory_story"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "story list"},
        ),
        migrations.AlterModelTable(
            name="story",
            table="Story",
        ),
    ]
