# Generated by Django 3.2.10 on 2022-01-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwtapp", "0006_auto_20220104_1013"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="story",
            table="story",
        ),
    ]
